services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: actix
      POSTGRES_PASSWORD: actix
      POSTGRES_DB: actix
    volumes:
      - ./data:/var/lib/postgresql/data
